app = "autocoinbot"
primary_region = "gru"

[build]
  image = "python:3.12"

[env]
  PORT = "8501"

[[services]]
  internal_port = 8501
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [services.health_check]
    interval = "30s"
    timeout = "5s"
    grace_period = "30s"
    path = "/"
    protocol = "http"
    method = "get"
